FROM hybsearch/libs:alpine AS build-deps

RUN apk add --no-cache -U autoconf automake g++ gcc make

FROM build-deps AS build

RUN curl -fsSL "https://github.com/hybsearch/jml/archive/v1.3.1.tar.gz" | gunzip - | tar -xv

WORKDIR /jml-1.3.1/src

ARG cores=4

RUN make -j$cores
RUN mv ./jml /usr/local/bin/jml

FROM hybsearch/libs:alpine

COPY --from=build ["/usr/local/bin/jml", "/usr/local/bin/jml"]
