---
version: 2

x-defs:
  - &defaults
    docker:
      - image: docker
  - &caches
    - &cache-load-docker
      keys:
        - docker--{{ .Environment.CIRCLE_JOB }}--{{ arch }}-{{ .Branch }}-{{ .Revision }}
        - docker--{{ .Environment.CIRCLE_JOB }}--{{ arch }}-{{ .Branch }}
        - docker--{{ .Environment.CIRCLE_JOB }}--{{ arch }}
    - &cache-save-docker
      key: docker--{{ .Environment.CIRCLE_JOB }}--{{ arch }}-{{ .Branch }}-{{ .Revision }}
      paths:
        - /tmp/image.tar
  - &docker-dump-image
    name: 'Dump image'
    command: >-
      docker save "hybsearch/$(echo $CIRCLE_JOB | cut -d'-' -f1):$CIRCLE_SHA1" > /tmp/image.tar
  - &docker-build-circle-job-image
    name: "Build the Docker Image"
    command: >-
      docker build --cache-from="$(docker images --quiet --all)"
      -t "hybsearch/$(echo $CIRCLE_JOB | cut -d'-' -f1):$CIRCLE_SHA1"
      -f "./$(echo $CIRCLE_JOB | cut -d'-' -f1)/Dockerfile.$(echo $CIRCLE_JOB | cut -d'-' -f2)"
      "./$(echo $CIRCLE_JOB | cut -d'-' -f2)/"

workflows:
  version: 2
  on_commit:
    jobs: &jobs
      - base-stretch
      # - base-alpine
      # - libs
      # - java
      # - clustalo
      # - jml
      # - mr-bayes
      # - seq-gen
      # - beast

  # cron_weekly:
  #   jobs: *jobs
  #   triggers:
  #     - schedule:
  #         # only run Monday morning at 12:00am
  #         cron: 0 */6 * * *
  #         filters:
  #           branches:
  #             only: [master]

jobs:
  base-stretch:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache: *cache-load-docker
      - run: *docker-build-circle-job-image
      - run: *docker-dump-image
      - save_cache: *cache-save-docker
