FROM hybsearch/libs:stretch

# fixes issue with installing openjdk-8-jdk-headless
RUN mkdir -p /usr/share/man/man1/

RUN apt-get update \
    && apt-get install -qy --no-install-recommends \
       openjdk-8-jdk-headless \
    && apt-get clean autoclean \
    && rm -rfv /var/lib/apt/ \
               /var/lib/cache/ \
               /var/lib/log/
