FROM hybsearch/java:stretch

RUN apt-get update \
    && apt-get install -qy --no-install-recommends \
       curl \
    && apt-get clean autoclean \
    && rm -rfv /var/lib/apt/ \
               /var/lib/dpkg/ \
               /var/lib/cache/ \
               /var/lib/log/

WORKDIR /beast
RUN curl -fsSL "https://github.com/CompEvol/beast2/releases/download/v2.4.8/BEAST.v2.4.8.Linux.tgz" | gunzip - | tar -xv
