FROM hybsearch/libs:alpine AS build

RUN apk add --no-cache -U \
    automake autoconf gcc g++ make \
    curl

RUN curl -fsSL "https://github.com/hybsearch/clustalo/archive/v1.2.4.tar.gz" | gunzip - | tar -xv

FROM hybsearch/libs:alpine
