FROM docker.io/debian:stretch-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       ca-certificates \
       curl \
    && apt-get clean autoclean \
    && rm -rfv /var/lib/apt/ \
               /var/lib/cache/ \
               /var/lib/log/
