FROM docker.io/debian:stretch-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       autoconf \
       automake \
       build-essential \
       ca-certificates \
       git \
       libtool \
       pkg-config \
    && apt-get clean autoclean \
    && rm -rfv /var/lib/apt/ \
               /var/lib/dpkg/ \
               /var/lib/cache/ \
               /var/lib/log/
